### ISSUE TITLE
Validation for hashed id

### ISSUE THREAD

**Issue by baggio85** [erashdan/hashid#15]
Hi Emad,
thanks a lot for this lovely package, I really like it a lot.
I just though about making a rule or validation like 'exists:App\Post,hashed_id' to check if this hashed id is a valid hashed id and if the id is exists in the same validation.

Let me know if its doable or needed any help in this update

**Comment by erashdan** [comment]
Hello @baggio85 

Thanks a lot 😄  
Yes it should be doable, I hope I can make it soon

**Comment by erashdan** [comment]
@baggio85 please check readme.md in pull request
https://github.com/erashdan/hashid/blob/96c8a141f1c9859093ff0697db99529e68ad3124/readme.md#validation

That's what you are looking for right?

**Comment by baggio85** [comment]
Thanks a lot, exactly that's what I meant appreciated
